[cursor.style]
blinking = "Always"
shape = "Block"

[font]
normal ={ family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 18.0

[scrolling]
history = 100000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
opacity = 0.8
startup_mode = "SimpleFullscreen"
