[cursor.style]
blinking = "Always"
shape = "Block"

[font]
normal ={ family = "JetbrainsMono Nerd Font", style = "regular" }
size = 14.0

[scrolling]
history = 100000
multiplier = 3

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux attach || tmux"] }

[window]
opacity = 1
startup_mode = "SimpleFullscreen"
